USE [master]
GO
/****** Object:  Database [OpClientes_DW]    Script Date: 3/5/2026 8:45:27 PM ******/
CREATE DATABASE [OpClientes_DW]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OpClientes_DW', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLSERVERITLA\MSSQL\DATA\OpClientes_DW.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OpClientes_DW_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLSERVERITLA\MSSQL\DATA\OpClientes_DW_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [OpClientes_DW] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OpClientes_DW].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [OpClientes_DW] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [OpClientes_DW] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [OpClientes_DW] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [OpClientes_DW] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [OpClientes_DW] SET ARITHABORT OFF 
GO
ALTER DATABASE [OpClientes_DW] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [OpClientes_DW] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [OpClientes_DW] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [OpClientes_DW] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [OpClientes_DW] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [OpClientes_DW] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [OpClientes_DW] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [OpClientes_DW] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [OpClientes_DW] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [OpClientes_DW] SET  ENABLE_BROKER 
GO
ALTER DATABASE [OpClientes_DW] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [OpClientes_DW] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [OpClientes_DW] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [OpClientes_DW] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [OpClientes_DW] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [OpClientes_DW] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [OpClientes_DW] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [OpClientes_DW] SET RECOVERY FULL 
GO
ALTER DATABASE [OpClientes_DW] SET  MULTI_USER 
GO
ALTER DATABASE [OpClientes_DW] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [OpClientes_DW] SET DB_CHAINING OFF 
GO
ALTER DATABASE [OpClientes_DW] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [OpClientes_DW] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [OpClientes_DW] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [OpClientes_DW] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'OpClientes_DW', N'ON'
GO
ALTER DATABASE [OpClientes_DW] SET QUERY_STORE = ON
GO
ALTER DATABASE [OpClientes_DW] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [OpClientes_DW]
GO
/****** Object:  Table [dbo].[DIM_Cliente]    Script Date: 3/5/2026 8:45:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIM_Cliente](
	[ID_Cliente] [int] NOT NULL,
	[Nombre] [nvarchar](100) NOT NULL,
	[Email] [nvarchar](100) NOT NULL,
	[Pais] [nvarchar](50) NULL,
	[Edad] [tinyint] NULL,
	[TipoCliente] [nvarchar](20) NULL,
 CONSTRAINT [PK_DIM_Cliente] PRIMARY KEY CLUSTERED 
(
	[ID_Cliente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DIM_Fecha]    Script Date: 3/5/2026 8:45:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIM_Fecha](
	[ID_Fecha] [int] NOT NULL,
	[Fecha] [date] NOT NULL,
	[Dia] [tinyint] NOT NULL,
	[Mes] [tinyint] NOT NULL,
	[NombreMes] [nvarchar](20) NOT NULL,
	[Trimestre] [tinyint] NOT NULL,
	[Anio] [smallint] NOT NULL,
	[Semana] [tinyint] NOT NULL,
	[DiaSemana] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_DIM_Fecha] PRIMARY KEY CLUSTERED 
(
	[ID_Fecha] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DIM_Fuente]    Script Date: 3/5/2026 8:45:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIM_Fuente](
	[ID_Fuente] [int] NOT NULL,
	[TipoFuente] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_DIM_Fuente] PRIMARY KEY CLUSTERED 
(
	[ID_Fuente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DIM_Producto]    Script Date: 3/5/2026 8:45:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIM_Producto](
	[ID_Producto] [int] NOT NULL,
	[Nombre] [nvarchar](100) NOT NULL,
	[Categoria] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_DIM_Producto] PRIMARY KEY CLUSTERED 
(
	[ID_Producto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DIM_Rating]    Script Date: 3/5/2026 8:45:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIM_Rating](
	[Puntaje] [tinyint] NOT NULL,
	[Clasificacion] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_DIM_Rating] PRIMARY KEY CLUSTERED 
(
	[Puntaje] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FACT_Opiniones]    Script Date: 3/5/2026 8:45:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FACT_Opiniones](
	[ID_Opinion] [int] IDENTITY(1,1) NOT NULL,
	[ID_Fecha] [int] NOT NULL,
	[ID_Cliente] [int] NOT NULL,
	[ID_Producto] [int] NOT NULL,
	[ID_Fuente] [int] NOT NULL,
	[Puntaje] [tinyint] NOT NULL,
	[Canal] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_FACT] PRIMARY KEY CLUSTERED 
(
	[ID_Opinion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACT_Opiniones]  WITH CHECK ADD  CONSTRAINT [FK_FACT_Cliente] FOREIGN KEY([ID_Cliente])
REFERENCES [dbo].[DIM_Cliente] ([ID_Cliente])
GO
ALTER TABLE [dbo].[FACT_Opiniones] CHECK CONSTRAINT [FK_FACT_Cliente]
GO
ALTER TABLE [dbo].[FACT_Opiniones]  WITH CHECK ADD  CONSTRAINT [FK_FACT_Fecha] FOREIGN KEY([ID_Fecha])
REFERENCES [dbo].[DIM_Fecha] ([ID_Fecha])
GO
ALTER TABLE [dbo].[FACT_Opiniones] CHECK CONSTRAINT [FK_FACT_Fecha]
GO
ALTER TABLE [dbo].[FACT_Opiniones]  WITH CHECK ADD  CONSTRAINT [FK_FACT_Fuente] FOREIGN KEY([ID_Fuente])
REFERENCES [dbo].[DIM_Fuente] ([ID_Fuente])
GO
ALTER TABLE [dbo].[FACT_Opiniones] CHECK CONSTRAINT [FK_FACT_Fuente]
GO
ALTER TABLE [dbo].[FACT_Opiniones]  WITH CHECK ADD  CONSTRAINT [FK_FACT_Producto] FOREIGN KEY([ID_Producto])
REFERENCES [dbo].[DIM_Producto] ([ID_Producto])
GO
ALTER TABLE [dbo].[FACT_Opiniones] CHECK CONSTRAINT [FK_FACT_Producto]
GO
ALTER TABLE [dbo].[FACT_Opiniones]  WITH CHECK ADD  CONSTRAINT [FK_FACT_Rating] FOREIGN KEY([Puntaje])
REFERENCES [dbo].[DIM_Rating] ([Puntaje])
GO
ALTER TABLE [dbo].[FACT_Opiniones] CHECK CONSTRAINT [FK_FACT_Rating]
GO
USE [master]
GO
ALTER DATABASE [OpClientes_DW] SET  READ_WRITE 
GO
