USE [master]
GO
/****** Object:  Database [OpClientes]    Script Date: 2/6/2026 9:17:03 PM ******/
CREATE DATABASE [OpClientes]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OpClientes', FILENAME = N'D:\Data\CURRENT\OpClientes.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ), 
 FILEGROUP [SECUNDARY] 
( NAME = N'OpClientes_sec', FILENAME = N'D:\Data\SECUNDARY\OpClientes_sec.ndf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OpClientes_log', FILENAME = N'D:\Data\HISTORY\OpClientes_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [OpClientes] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OpClientes].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [OpClientes] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [OpClientes] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [OpClientes] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [OpClientes] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [OpClientes] SET ARITHABORT OFF 
GO
ALTER DATABASE [OpClientes] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [OpClientes] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [OpClientes] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [OpClientes] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [OpClientes] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [OpClientes] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [OpClientes] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [OpClientes] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [OpClientes] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [OpClientes] SET  DISABLE_BROKER 
GO
ALTER DATABASE [OpClientes] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [OpClientes] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [OpClientes] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [OpClientes] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [OpClientes] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [OpClientes] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [OpClientes] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [OpClientes] SET RECOVERY FULL 
GO
ALTER DATABASE [OpClientes] SET  MULTI_USER 
GO
ALTER DATABASE [OpClientes] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [OpClientes] SET DB_CHAINING OFF 
GO
ALTER DATABASE [OpClientes] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [OpClientes] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [OpClientes] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [OpClientes] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'OpClientes', N'ON'
GO
ALTER DATABASE [OpClientes] SET QUERY_STORE = ON
GO
ALTER DATABASE [OpClientes] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [OpClientes]
GO
/****** Object:  Table [dbo].[Categorias]    Script Date: 2/6/2026 9:17:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categorias](
	[ID_Categoria] [int] IDENTITY(1,1) NOT NULL,
	[TipoCategoria] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Categorias] PRIMARY KEY CLUSTERED 
(
	[ID_Categoria] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Clientes]    Script Date: 2/6/2026 9:17:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Clientes](
	[ID_Cliente] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](100) NOT NULL,
	[Email] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_Clientes] PRIMARY KEY CLUSTERED 
(
	[ID_Cliente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Comentarios]    Script Date: 2/6/2026 9:17:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Comentarios](
	[ID_Comentario] [int] IDENTITY(1,1) NOT NULL,
	[Texto_Comentario] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Comentarios_1] PRIMARY KEY CLUSTERED 
(
	[ID_Comentario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Fuentes]    Script Date: 2/6/2026 9:17:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Fuentes](
	[ID_Fuente] [int] IDENTITY(1,1) NOT NULL,
	[TipoFuente] [nvarchar](50) NOT NULL,
	[FechaCarga] [datetime2](0) NOT NULL,
 CONSTRAINT [PK_Fuentes] PRIMARY KEY CLUSTERED 
(
	[ID_Fuente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Producto]    Script Date: 2/6/2026 9:17:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Producto](
	[ID_Producto] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](100) NOT NULL,
	[ID_Categoria] [int] NOT NULL,
 CONSTRAINT [PK_Producto] PRIMARY KEY CLUSTERED 
(
	[ID_Producto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Rating]    Script Date: 2/6/2026 9:17:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Rating](
	[Puntaje] [tinyint] NOT NULL,
	[Clasificación] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_Rating] PRIMARY KEY CLUSTERED 
(
	[Puntaje] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SocialComments]    Script Date: 2/6/2026 9:17:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SocialComments](
	[ID_SocialC] [int] IDENTITY(1,1) NOT NULL,
	[Fecha] [date] NOT NULL,
	[ID_Cliente] [int] NOT NULL,
	[ID_Producto] [int] NOT NULL,
	[ID_Fuente] [int] NOT NULL,
	[ID_Comentario] [int] NOT NULL,
 CONSTRAINT [PK_SocialComments] PRIMARY KEY CLUSTERED 
(
	[ID_SocialC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Survey]    Script Date: 2/6/2026 9:17:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Survey](
	[ID_Survey] [int] IDENTITY(1,1) NOT NULL,
	[Fecha] [date] NOT NULL,
	[Puntaje] [tinyint] NOT NULL,
	[ID_Cliente] [int] NOT NULL,
	[ID_Producto] [int] NOT NULL,
	[ID_Fuente] [int] NOT NULL,
	[ID_Comentario] [int] NOT NULL,
 CONSTRAINT [PK_Survey] PRIMARY KEY CLUSTERED 
(
	[ID_Survey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[WebReviews]    Script Date: 2/6/2026 9:17:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WebReviews](
	[ID_Review] [int] IDENTITY(1,1) NOT NULL,
	[Fecha] [date] NOT NULL,
	[Puntaje] [tinyint] NOT NULL,
	[ID_Cliente] [int] NOT NULL,
	[ID_Producto] [int] NOT NULL,
	[ID_Fuente] [int] NOT NULL,
	[ID_Comentario] [int] NOT NULL,
 CONSTRAINT [PK_WebReviews] PRIMARY KEY CLUSTERED 
(
	[ID_Review] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ_Clientes_Email]    Script Date: 2/6/2026 9:17:03 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UQ_Clientes_Email] ON [dbo].[Clientes]
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_SocialComments_ID_Cliente]    Script Date: 2/6/2026 9:17:03 PM ******/
CREATE NONCLUSTERED INDEX [IX_SocialComments_ID_Cliente] ON [dbo].[SocialComments]
(
	[ID_Cliente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_SocialComments_ID_Fuente]    Script Date: 2/6/2026 9:17:03 PM ******/
CREATE NONCLUSTERED INDEX [IX_SocialComments_ID_Fuente] ON [dbo].[SocialComments]
(
	[ID_Fuente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_SocialComments_ID_Producto]    Script Date: 2/6/2026 9:17:03 PM ******/
CREATE NONCLUSTERED INDEX [IX_SocialComments_ID_Producto] ON [dbo].[SocialComments]
(
	[ID_Producto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Survey_Fecha]    Script Date: 2/6/2026 9:17:03 PM ******/
CREATE NONCLUSTERED INDEX [IX_Survey_Fecha] ON [dbo].[Survey]
(
	[Fecha] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Survey_ID_Cliente]    Script Date: 2/6/2026 9:17:03 PM ******/
CREATE NONCLUSTERED INDEX [IX_Survey_ID_Cliente] ON [dbo].[Survey]
(
	[ID_Cliente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Survey_ID_Fuente]    Script Date: 2/6/2026 9:17:03 PM ******/
CREATE NONCLUSTERED INDEX [IX_Survey_ID_Fuente] ON [dbo].[Survey]
(
	[ID_Fuente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Survey_ID_Producto]    Script Date: 2/6/2026 9:17:03 PM ******/
CREATE NONCLUSTERED INDEX [IX_Survey_ID_Producto] ON [dbo].[Survey]
(
	[ID_Producto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_WebReviews_Fecha]    Script Date: 2/6/2026 9:17:03 PM ******/
CREATE NONCLUSTERED INDEX [IX_WebReviews_Fecha] ON [dbo].[WebReviews]
(
	[Fecha] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_WebReviews_ID_Cliente]    Script Date: 2/6/2026 9:17:03 PM ******/
CREATE NONCLUSTERED INDEX [IX_WebReviews_ID_Cliente] ON [dbo].[WebReviews]
(
	[ID_Cliente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_WebReviews_ID_Fuente]    Script Date: 2/6/2026 9:17:03 PM ******/
CREATE NONCLUSTERED INDEX [IX_WebReviews_ID_Fuente] ON [dbo].[WebReviews]
(
	[ID_Fuente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_WebReviews_ID_Producto]    Script Date: 2/6/2026 9:17:03 PM ******/
CREATE NONCLUSTERED INDEX [IX_WebReviews_ID_Producto] ON [dbo].[WebReviews]
(
	[ID_Producto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Producto]  WITH CHECK ADD  CONSTRAINT [FK_Producto_Categorias] FOREIGN KEY([ID_Categoria])
REFERENCES [dbo].[Categorias] ([ID_Categoria])
GO
ALTER TABLE [dbo].[Producto] CHECK CONSTRAINT [FK_Producto_Categorias]
GO
ALTER TABLE [dbo].[SocialComments]  WITH CHECK ADD  CONSTRAINT [FK_SocialComments_Clientes] FOREIGN KEY([ID_Cliente])
REFERENCES [dbo].[Clientes] ([ID_Cliente])
GO
ALTER TABLE [dbo].[SocialComments] CHECK CONSTRAINT [FK_SocialComments_Clientes]
GO
ALTER TABLE [dbo].[SocialComments]  WITH CHECK ADD  CONSTRAINT [FK_SocialComments_Comentarios1] FOREIGN KEY([ID_Comentario])
REFERENCES [dbo].[Comentarios] ([ID_Comentario])
GO
ALTER TABLE [dbo].[SocialComments] CHECK CONSTRAINT [FK_SocialComments_Comentarios1]
GO
ALTER TABLE [dbo].[SocialComments]  WITH CHECK ADD  CONSTRAINT [FK_SocialComments_Fuentes] FOREIGN KEY([ID_Fuente])
REFERENCES [dbo].[Fuentes] ([ID_Fuente])
GO
ALTER TABLE [dbo].[SocialComments] CHECK CONSTRAINT [FK_SocialComments_Fuentes]
GO
ALTER TABLE [dbo].[SocialComments]  WITH CHECK ADD  CONSTRAINT [FK_SocialComments_Producto] FOREIGN KEY([ID_Producto])
REFERENCES [dbo].[Producto] ([ID_Producto])
GO
ALTER TABLE [dbo].[SocialComments] CHECK CONSTRAINT [FK_SocialComments_Producto]
GO
ALTER TABLE [dbo].[Survey]  WITH CHECK ADD  CONSTRAINT [FK_Survey_Clientes] FOREIGN KEY([ID_Cliente])
REFERENCES [dbo].[Clientes] ([ID_Cliente])
GO
ALTER TABLE [dbo].[Survey] CHECK CONSTRAINT [FK_Survey_Clientes]
GO
ALTER TABLE [dbo].[Survey]  WITH CHECK ADD  CONSTRAINT [FK_Survey_Comentarios1] FOREIGN KEY([ID_Comentario])
REFERENCES [dbo].[Comentarios] ([ID_Comentario])
GO
ALTER TABLE [dbo].[Survey] CHECK CONSTRAINT [FK_Survey_Comentarios1]
GO
ALTER TABLE [dbo].[Survey]  WITH CHECK ADD  CONSTRAINT [FK_Survey_Fuentes] FOREIGN KEY([ID_Fuente])
REFERENCES [dbo].[Fuentes] ([ID_Fuente])
GO
ALTER TABLE [dbo].[Survey] CHECK CONSTRAINT [FK_Survey_Fuentes]
GO
ALTER TABLE [dbo].[Survey]  WITH CHECK ADD  CONSTRAINT [FK_Survey_Producto] FOREIGN KEY([ID_Producto])
REFERENCES [dbo].[Producto] ([ID_Producto])
GO
ALTER TABLE [dbo].[Survey] CHECK CONSTRAINT [FK_Survey_Producto]
GO
ALTER TABLE [dbo].[Survey]  WITH CHECK ADD  CONSTRAINT [FK_Survey_Rating] FOREIGN KEY([Puntaje])
REFERENCES [dbo].[Rating] ([Puntaje])
GO
ALTER TABLE [dbo].[Survey] CHECK CONSTRAINT [FK_Survey_Rating]
GO
ALTER TABLE [dbo].[WebReviews]  WITH CHECK ADD  CONSTRAINT [FK_WebReviews_Clientes] FOREIGN KEY([ID_Cliente])
REFERENCES [dbo].[Clientes] ([ID_Cliente])
GO
ALTER TABLE [dbo].[WebReviews] CHECK CONSTRAINT [FK_WebReviews_Clientes]
GO
ALTER TABLE [dbo].[WebReviews]  WITH CHECK ADD  CONSTRAINT [FK_WebReviews_Comentarios1] FOREIGN KEY([ID_Comentario])
REFERENCES [dbo].[Comentarios] ([ID_Comentario])
GO
ALTER TABLE [dbo].[WebReviews] CHECK CONSTRAINT [FK_WebReviews_Comentarios1]
GO
ALTER TABLE [dbo].[WebReviews]  WITH CHECK ADD  CONSTRAINT [FK_WebReviews_Fuentes] FOREIGN KEY([ID_Fuente])
REFERENCES [dbo].[Fuentes] ([ID_Fuente])
GO
ALTER TABLE [dbo].[WebReviews] CHECK CONSTRAINT [FK_WebReviews_Fuentes]
GO
ALTER TABLE [dbo].[WebReviews]  WITH CHECK ADD  CONSTRAINT [FK_WebReviews_Producto] FOREIGN KEY([ID_Producto])
REFERENCES [dbo].[Producto] ([ID_Producto])
GO
ALTER TABLE [dbo].[WebReviews] CHECK CONSTRAINT [FK_WebReviews_Producto]
GO
ALTER TABLE [dbo].[WebReviews]  WITH CHECK ADD  CONSTRAINT [FK_WebReviews_Rating] FOREIGN KEY([Puntaje])
REFERENCES [dbo].[Rating] ([Puntaje])
GO
ALTER TABLE [dbo].[WebReviews] CHECK CONSTRAINT [FK_WebReviews_Rating]
GO
ALTER TABLE [dbo].[Rating]  WITH CHECK ADD  CONSTRAINT [CK_Rating_Puntaje] CHECK  (([Puntaje]>=(1) AND [Puntaje]<=(5)))
GO
ALTER TABLE [dbo].[Rating] CHECK CONSTRAINT [CK_Rating_Puntaje]
GO
USE [master]
GO
ALTER DATABASE [OpClientes] SET  READ_WRITE 
GO
